stages:
  data_ingestion:
    cmd: python src/data/make_dataset.py
    deps:
    - src/data/make_dataset.py
    outs:
    - data/raw/Reviews.csv

  data_preprocess:
    cmd: python src/features/build_features.py
    deps:
    - src/features/build_features.py
    - data/raw/Reviews.csv
    outs:
    - data/processed/user_item_matrix.csv
    - data/processed/user_mapping.csv
    - data/processed/item_mapping.csv

  train_model:
    cmd: python src/models/train_model.py
    deps:
    - data/processed/user_item_matrix.csv
    - src/models/train_model.py
    params:
    - model.n_components
    - model.max_iter
    - model.random_state
    outs:
    - models/matrix_factorization_model.pkl
    - models/user_factors.csv
    - models/item_factors.csv

  evaluate_model:
    cmd: python src/models/predict_model.py
    deps:
    - data/processed/user_item_matrix.csv
    - models/matrix_factorization_model.pkl
    - models/user_factors.csv
    - models/item_factors.csv
    - src/models/predict_model.py
    params:
    - evaluate.top_k
    - evaluate.test_size
    metrics:
    - metrics/reconstruction_error.json:
        cache: false
    - metrics/recommendation_metrics.json:
        cache: false
