stages:
  data_ingestion:
    cmd: python src/data/make_dataset.py
    deps:
    - src/data/make_dataset.py
    outs:
    - data/raw/Reviews.csv

  data_preprocess:
    cmd: python src/features/build_features.py
    deps:
    - src/features/build_features.py
    - data/raw/Reviews.csv
    outs:
    - data/processed/processed_reviews.csv

  train_model:
    cmd: python src/models/train_model.py
    deps:
    - data/processed/processed_reviews.csv
    - src/models/train_model.py
    params:
    - train.min_user_interactions
    - train.min_product_interactions
    - train.metric
    - train.neighbors
    outs:
    - models/knn_model.pkl

  evaluate_model:
    cmd: python src/models/predict_model.py
    deps:
    - data/processed/processed_reviews.csv
    - models/knn_model.pkl
    - src/models/predict_model.py
    params:
    - evaluate.top_k
    - evaluate.eval_user_count
    - evaluate.rating_threshold
    metrics:
    - metrics/recall.json:
        cache: false
